version: '2'
services:
    skulman-app:
        image: skulman
        external_links:
            - skulman-mysql:mysql
            - skulman-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/skulman?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    skulman-mysql:
        extends:
            file: mysql.yml
            service: skulman-mysql
    skulman-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: skulman-elasticsearch
